import type { RunResult } from '../types/contracts.js';
import { config } from '../config.js';

export interface PullRequestBody {
  title: string;
  body: string;
  riskNotes: string[];
}

function buildRiskNotes(run: RunResult): string[] {
  const notes: string[] = [];
  const validation = run.validation;
  const analysis = run.analysis;
  const changedCount = analysis?.changedFiles?.length ?? 0;

  notes.push('This PR was opened by the bug-fix automation orchestrator after manual approval.');
  notes.push('**Do not auto-merge** — review the diff on GitHub before merging.');

  if (analysis?.implementationNote?.includes('dry-run')) {
    notes.push('Agent ran in dry-run mode; patch may be incomplete or absent.');
  }

  if (changedCount === 0) {
    notes.push('No changed files detected — verify the branch contains the expected fix.');
  } else if (changedCount > 5) {
    notes.push(`Wide touch surface (${changedCount} files) — extra scrutiny recommended.`);
  }

  if (validation && !validation.buildPassed) {
    notes.push('Local backend and/or frontend build did not fully pass validation.');
  }
  if (validation && !validation.testsPassed) {
    notes.push('Local automated tests did not fully pass or were not run.');
  }
  if (validation?.failureReason) {
    notes.push(`Validation note: ${validation.failureReason}`);
  }
  if (validation?.testGapRecommendations?.length) {
    notes.push('Test coverage is minimal; see validation test gap recommendations in run artifacts.');
  }
  if (validation && !validation.strictMode && validation.build?.frontend && !validation.build.frontend.success) {
    notes.push('Frontend production build failed but demo policy (STRICT_VALIDATION=false) allowed approval.');
  }

  notes.push('No CI/CD or deployment steps are triggered by this automation.');
  return notes;
}

export function buildPullRequestContent(run: RunResult, overrides?: { title?: string; bodyPrefix?: string }): PullRequestBody {
  const { intake, analysis, validation, git, approval, runId } = run;
  const changedFiles = analysis?.changedFiles ?? [];
  const riskNotes = buildRiskNotes(run);

  const title =
    overrides?.title?.trim() ||
    `fix: ${intake.bug.title}`.slice(0, 256);

  const validationLines = validation
    ? [
        `| Check | Result |`,
        `|-------|--------|`,
        `| Overall passed | ${validation.passed} |`,
        `| Build passed | ${validation.buildPassed} |`,
        `| Tests passed | ${validation.testsPassed} |`,
        `| Test summary | ${validation.testSummary} |`,
        validation.failureReason ? `| Failure reason | ${validation.failureReason} |` : '',
      ].filter(Boolean)
    : ['_(validation not available)_'];

  const body = [
    overrides?.bodyPrefix ? `${overrides.bodyPrefix}\n` : '',
    `## Bug summary`,
    analysis?.bugSummary || intake.bug.description,
    '',
    `## Root cause`,
    analysis?.rootCauseSummary || '_Not determined by agent._',
    '',
    `## Branch`,
    `- **Feature branch:** \`${git?.branchName ?? 'n/a'}\``,
    `- **Base branch:** \`${git?.baseBranch ?? config.defaultBaseBranch}\``,
    `- **Run ID:** \`${runId}\``,
    '',
    `## Files changed (${changedFiles.length})`,
    changedFiles.length > 0
      ? changedFiles.map((f) => `- \`${f}\``).join('\n')
      : '- _(none detected)_',
    '',
    `## Local validation results`,
    ...validationLines,
    '',
    `## Risk notes`,
    ...riskNotes.map((n) => `- ${n}`),
    '',
    `## Approval`,
    `- **Approved by:** ${approval.approvedBy ?? 'n/a'}`,
    approval.approvedAt ? `- **Approved at:** ${approval.approvedAt}` : '',
    approval.comment ? `- **Reviewer comment:** ${approval.comment}` : '',
    '',
    `---`,
    `_Generated by bug-fix orchestrator. Artifacts: \`${run.artifactsPath}\`_`,
  ]
    .filter(Boolean)
    .join('\n');

  return { title, body, riskNotes };
}
